services:
  - type: web
    name: ome-chat-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: ''
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: CORS_ORIGIN
        value: https://frontend-ewtplmw11-sajids-projects-6524aee0.vercel.app
    healthCheckPath: /
    region: oregon
